### ISSUE TITLE
change hardcoded permission id

### ISSUE THREAD

**Issue by JoseFilipeFerreira** [RisingFisan/WALL-E#1]
In several parts of the code the owner/super user of the bot is hardcoded.
There are better options

In the case of commands that are owner only you could add the decorator
```python
@commands.is_owner()
```

In the case of using the id in the middle of the code you could use
```python
app_info = await bot.application_info()
id = app_info.owner.id
```

**Comment by RisingFisan** [comment]
The first option is not suitable in this case because I want the bot to send an error message if the user doesn't have permissions to run the command, something that afaik isn't doable with that implementation, but the second option is a solid one, I may do something similar to that in a future commit.

**Comment by JoseFilipeFerreira** [comment]
There are ways to write custom error messages for each permission breach

**Comment by RisingFisan** [comment]
You're right, I didn't know that! It's implemented now.
